package edu.only4.danmuku.adapter.portal.api.payload.video_encrypt

import org.mapstruct.Mapper
import org.mapstruct.factory.Mappers

/**
 * Frontend: list encrypted qualities (with current user playable status)
 *
 * This file is generated by [cap4k-ddd-codegen-gradle-plugin]
 * @author cap4k-ddd-codegen
 * @date 2025/12/19
 */
object GetVideEncVariants {

    data class Request(
        val fileId: Long
    )

    data class QualityItem(
        val quality: String,
        val authPolicy: Int,
        val playable: Boolean
    )

    data class Response(
        val qualities: List<QualityItem>
    )

    @Mapper(componentModel = "default")
    interface Converter {
        companion object {
            val INSTANCE: Converter = Mappers.getMapper(Converter::class.java)
        }
    }
}
