# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# Kotlin ecosystem
kotlin = "2.2.20"
ksp = "2.2.20-2.0.2"
mapstruct = "1.6.2"

# Spring framework
spring-boot = "3.5.6"
spring-dependency-management = "1.1.3"
blazebit = "1.6.12"

# Tools
hutool = "5.8.40"

only-engine = "0.1.12-SNAPSHOT"
cap4k = "0.5.0-SNAPSHOT"
jimmer = "0.9.106"

hibernate-core = "7.0.10.Final"

# Testing
junit = "5.13.4"
mockk = "1.13.8"
kotlin-compile-testing = "0.8.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen-plugin = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-noarg-plugin = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin" }

# Spring framework
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-data = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-messaging = { module = "org.springframework:spring-messaging", version.ref = "spring-boot" }

annotation = { module = "jakarta.annotation:jakarta.annotation-api" }
blazebit-persistence-querydsl = { module = "com.blazebit:blaze-persistence-integration-querydsl-expressions-jakarta", version.ref = "blazebit" }
blazebit-persistence-hibernate = { module = "com.blazebit:blaze-persistence-integration-hibernate-6.2", version.ref = "blazebit" }

# Tools
hutool-jwt = { module = "cn.hutool:hutool-jwt", version.ref = "hutool" }
hutool-core = { module = "cn.hutool:hutool-core", version.ref = "hutool" }
hutool-extra = { module = "cn.hutool:hutool-extra", version.ref = "hutool" }
hutool-crypto = { module = "cn.hutool:hutool-crypto", version.ref = "hutool" }
hutool-http = { module = "cn.hutool:hutool-http", version.ref = "hutool" }
hutool-captcha = { module = "cn.hutool:hutool-captcha", version.ref = "hutool" }

engine-common = { module = "com.only4:engine-common", version.ref = "only-engine" }
engine-captcha = { module = "com.only4:engine-captcha", version.ref = "only-engine" }
engine-security = { module = "com.only4:engine-security", version.ref = "only-engine" }
engine-satoken = { module = "com.only4:engine-satoken", version.ref = "only-engine" }
engine-redis = { module = "com.only4:engine-redis", version.ref = "only-engine" }
engine-json = { module = "com.only4:engine-json", version.ref = "only-engine" }
engine-web = { module = "com.only4:engine-web", version.ref = "only-engine" }
engine-doc = { module = "com.only4:engine-doc", version.ref = "only-engine" }
engine-translation = { module = "com.only4:engine-translation", version.ref = "only-engine" }
engine-oss = { module = "com.only4:engine-oss", version.ref = "only-engine" }

cap4k-console = { module = "com.only4:cap4k-ddd-console", version.ref = "cap4k" }
cap4k-plugin-code-analysis-compiler = { module = "com.only4:cap4k-plugin-code-analysis-compiler", version.ref = "cap4k" }
cap4k-plugin-code-analysis-core = { module = "com.only4:cap4k-plugin-code-analysis-core", version.ref = "cap4k" }
ddd-starter = { module = "com.only4:cap4k-ddd-starter", version.ref = "cap4k" }
ddd-integration-event-http = { module = "com.only4:ddd-integration-event-http", version.ref = "cap4k" }
ddd-integration-event-http-jpa = { module = "com.only4:ddd-integration-event-http-jpa", version.ref = "cap4k" }

jimmer-starter = { module = "org.babyfish.jimmer:jimmer-spring-boot-starter", version.ref = "jimmer" }
jimmer-core = { module = "org.babyfish.jimmer:jimmer-core-kotlin", version.ref = "jimmer" }
jimmer-sql = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
jimmer-ksp = { module = "org.babyfish.jimmer:jimmer-ksp", version.ref = "jimmer" }

hibernate-processor = { module = "org.hibernate.orm:hibernate-processor", version.ref = "hibernate-core" }

# MapStruct
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

druid = { module = "com.alibaba:druid-spring-boot-starter", version = "1.2.8" }
mysql = { module = "com.mysql:mysql-connector-j", version = "8.1.0" }
h2 = { module = "com.h2database:h2", version = "2.3.232" }

# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kotlin-compile-testing" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }

# Libraries can be bundled together for easier import
[bundles]
junit-core = ["junit-jupiter-api", "junit-jupiter-params"]
junit-runtime = ["junit-jupiter-engine", "junit-platform-launcher"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
